'use client';
import { Outlet } from 'react-router-dom';
import './global.css';
import Layout from './components/layout';

// const metadata = {
//   title: 'Welcome to nesamaju-profile',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout></Layout>
        <Outlet />
        {children}
      </body>
    </html>
  );
}
